### PR TITLE
Remove XForms documentation (part of php/doc-en#3579)

### PR DESCRIPTION
**Pull request by jimwins**
Removes the translation in advance of it being removed entirely.

### CODE REVIEW

**Comment by jimwins** [comment]
The checks are failing because of the issue addressed by PR #121.

**Comment by mumumu** [comment]
This PR will be approved, shortly after xforms.xml (and its reference) is removed from doc-en and doc-base.

Until they are removed, the checks will continue to fail indefinitely.

**Comment by mumumu** [comment]
partially applied in https://github.com/php/doc-ja/commit/927a1f8d297dc7be423e037e2bdbb3af94e02026

**Comment by jimwins** [comment]
Okay, removal of `features/xforms.xml` can happen in a different PR, going to just close this one.

**Pull request closed without merging**
